// AUTO-GENERATED by hirct-gen — DO NOT EDIT
// verilog_lint: waive-start module-filename
module uart_top (
    UART_PCLK,
    UART_PRESETn,
    UART_CLK,
    UART_RESETn,
    PSEL,
    PENABLE,
    PWRITE,
    PADDR,
    PWDATA,
    PRDATA,
    UART0_INTR,
    UART1_INTR,
    UART0_TXD,
    UART0_RXD,
    UART1_TXD,
    UART1_RXD,
    SCAN_MODE
);

    input               UART_PCLK;
    input               UART_PRESETn;
    input               UART_CLK;
    input               UART_RESETn;
    input               PSEL;
    input               PENABLE;
    input               PWRITE;
    input   [23:0]      PADDR;
    input   [31:0]      PWDATA;
    output  [31:0]      PRDATA;
    output              UART0_INTR;
    output              UART1_INTR;
    output              UART0_TXD;
    input               UART0_RXD;
    output              UART1_TXD;
    input               UART1_RXD;
    input               SCAN_MODE;

    uart_top_dpi_wrapper u_dpi (
        .UART_PCLK   (UART_PCLK),
        .UART_PRESETn(UART_PRESETn),
        .UART_CLK    (UART_CLK),
        .UART_RESETn (UART_RESETn),
        .PSEL        (PSEL),
        .PENABLE     (PENABLE),
        .PWRITE      (PWRITE),
        .PADDR       (PADDR),
        .PWDATA      (PWDATA),
        .PRDATA      (PRDATA),
        .UART0_INTR  (UART0_INTR),
        .UART1_INTR  (UART1_INTR),
        .UART0_TXD   (UART0_TXD),
        .UART0_RXD   (UART0_RXD),
        .UART1_TXD   (UART1_TXD),
        .UART1_RXD   (UART1_RXD),
        .SCAN_MODE   (SCAN_MODE)
    );

endmodule
