// AUTO-GENERATED by hirct-gen — DO NOT EDIT
// CModel SV sources for topsim uart_top integration
// Used by: VCS (vlogan -f). For NC, see board.pt_plat_only.nc/Makefile anal_plat
// Replaces: ${PROJECT}/rtl/pt_plat/bin/lst/uart_file_list.f
-sverilog
$CMODEL_UART_BASE/dpi/uart_top_dpi.sv
$CMODEL_UART_BASE/topsim/uart_top_shim.sv
