// AUTO-GENERATED by hirct-gen — DO NOT EDIT
`timescale 1ns/1ps

module tb_DW_apb_uart_bcm99;

  // ── Parameters ────────────────────────────────────────────────────────
  int seed   = 42;
  int cycles = 1000;
  int warmup = 10;

  // ── Shared signals ────────────────────────────────────────────────────
  logic clk_d;
  logic rst_d_n;
  logic data_s;

  // ── RTL outputs ───────────────────────────────────────────────────────
  logic rtl_data_d;

  // ── DPI outputs ───────────────────────────────────────────────────────
  logic dpi_data_d;

  // ── RTL instance ──────────────────────────────────────────────────────
  DW_apb_uart_bcm99 u_rtl (
    .clk_d   (clk_d),
    .rst_d_n (rst_d_n),
    .data_s  (data_s),
    .data_d  (rtl_data_d)
  );

  // ── DPI-C wrapper instance ────────────────────────────────────────────
  DW_apb_uart_bcm99_dpi_wrapper u_dpi (
    .clk_d   (clk_d),
    .rst_d_n (rst_d_n),
    .data_s  (data_s),
    .data_d  (dpi_data_d)
  );

  // ── Clock generation (10 ns period) ───────────────────────────────────
  initial clk_d = 0;
  always #5 clk_d = ~clk_d;

  // ── Waveform dump (plusarg-controlled) ──────────────────────────────────
  initial begin
    reg [8*64-1:0] dump_fmt;
    if ($value$plusargs("dump=%s", dump_fmt)) begin
`ifdef VCS
      if (dump_fmt == "fsdb") begin
        $fsdbDumpfile("waves.fsdb");
        $fsdbDumpvars(0, tb_DW_apb_uart_bcm99);
        $fsdbDumpMDA;
      end else
`endif
      if (dump_fmt == "vcd") begin
        $dumpfile("waves.vcd");
        $dumpvars(0, tb_DW_apb_uart_bcm99);
      end
    end
  end

  // ── Main stimulus ─────────────────────────────────────────────────────
  int pass_count;
  int fail_count;

  initial begin
    if ($value$plusargs("seed=%d", seed))   ;
    if ($value$plusargs("cycles=%d", cycles)) ;
    if ($value$plusargs("warmup=%d", warmup)) ;
    process::self().srandom(seed);

    pass_count = 0;
    fail_count = 0;

    // ── Reset phase (active-low rst_d_n) ─────────────────────────────────
    rst_d_n = 0;
    data_s  = 0;

    repeat (10) @(posedge clk_d);
    rst_d_n = 1;

    // ── Warmup (no comparison) ───────────────────────────────────────────
    repeat (warmup) begin
      @(posedge clk_d);
      data_s = $urandom_range(0, 1);
    end

    // ── Comparison phase ────────────────────────────────────────────────
    repeat (cycles) begin
      @(posedge clk_d);
      data_s = $urandom_range(0, 1);

      @(negedge clk_d);
      if (rtl_data_d === dpi_data_d) begin
        pass_count++;
      end else begin
        fail_count++;
        $display("[MISMATCH] cycle=%0d: RTL data_d=%b  DPI data_d=%b",
                 pass_count + fail_count, rtl_data_d, dpi_data_d);
      end
    end

    // ── Summary ──────────────────────────────────────────────────────────
    if (fail_count == 0) begin
      $display("[PASS] seed=%0d: %0d matches, 0 mismatches", seed, pass_count);
      $display("RESULT: PASS");
    end else begin
      $display("[FAIL] seed=%0d: %0d matches, %0d mismatches",
               seed, pass_count, fail_count);
      $display("RESULT: FAIL %0d mismatches", fail_count);
      $fatal(1, "Co-simulation FAILED");
    end

    $finish;
  end

endmodule
