// AUTO-GENERATED by hirct-gen — DO NOT EDIT
`timescale 1ns/1ps

module tb_Fadu_K2_S5_LevelGateway;

  // ── Parameters ────────────────────────────────────────────────────────
  int seed   = 42;
  int cycles = 1000;

  // ── Shared signals ────────────────────────────────────────────────────
  logic preset_flops;
  logic clk;
  logic reset;
  logic io_interrupt;
  logic io_plic_ready;
  logic io_plic_complete;

  // ── RTL outputs ───────────────────────────────────────────────────────
  logic rtl_io_plic_valid;

  // ── DPI outputs ───────────────────────────────────────────────────────
  logic dpi_io_plic_valid;

  // ── RTL instance ──────────────────────────────────────────────────────
  Fadu_K2_S5_LevelGateway u_rtl (
    .preset_flops    (preset_flops),
    .clock           (clk),
    .reset           (reset),
    .io_interrupt    (io_interrupt),
    .io_plic_valid   (rtl_io_plic_valid),
    .io_plic_ready   (io_plic_ready),
    .io_plic_complete(io_plic_complete)
  );

  // ── DPI-C wrapper instance ────────────────────────────────────────────
  Fadu_K2_S5_LevelGateway_dpi_wrapper u_dpi (
    .preset_flops    (preset_flops),
    .clock           (clk),
    .reset           (reset),
    .io_interrupt    (io_interrupt),
    .io_plic_valid   (dpi_io_plic_valid),
    .io_plic_ready   (io_plic_ready),
    .io_plic_complete(io_plic_complete)
  );

  // ── Clock generation (10 ns period) ───────────────────────────────────
  initial clk = 0;
  always #5 clk = ~clk;

  // ── Waveform dump (plusarg-controlled) ──────────────────────────────────
  initial begin
    reg [8*64-1:0] dump_fmt;
    if ($value$plusargs("dump=%s", dump_fmt)) begin
`ifdef VCS
      if (dump_fmt == "fsdb") begin
        $fsdbDumpfile("waves.fsdb");
        $fsdbDumpvars(0, tb_Fadu_K2_S5_LevelGateway);
        $fsdbDumpMDA;
      end else
`endif
      if (dump_fmt == "vcd") begin
        $dumpfile("waves.vcd");
        $dumpvars(0, tb_Fadu_K2_S5_LevelGateway);
      end
    end
  end

  // ── Main stimulus ─────────────────────────────────────────────────────
  int pass_count;
  int fail_count;
  int warmup;

  initial begin
    if ($value$plusargs("seed=%d", seed))   ;
    if ($value$plusargs("cycles=%d", cycles)) ;
    process::self().srandom(seed);

    pass_count = 0;
    fail_count = 0;
    warmup     = 10;

    // ── Reset phase ───────────────────────────────────────────────────
    preset_flops    = 1;
    reset           = 1;
    io_interrupt    = 0;
    io_plic_ready   = 0;
    io_plic_complete = 0;

    @(posedge clk);
    preset_flops = 0;

    repeat (9) @(posedge clk);
    reset = 0;

    // ── Warmup (10 cycles, no comparison) ─────────────────────────────
    repeat (warmup) begin
      @(posedge clk);
      io_interrupt    = $urandom_range(0, 1);
      io_plic_ready   = $urandom_range(0, 1);
      io_plic_complete = $urandom_range(0, 1);
    end

    // ── Comparison phase ──────────────────────────────────────────────
    repeat (cycles) begin
      @(posedge clk);
      io_interrupt    = $urandom_range(0, 1);
      io_plic_ready   = $urandom_range(0, 1);
      io_plic_complete = $urandom_range(0, 1);

      @(negedge clk);
      if (rtl_io_plic_valid === dpi_io_plic_valid) begin
        pass_count++;
      end else begin
        fail_count++;
        $display("[MISMATCH] cycle=%0d: RTL io_plic_valid=%b  DPI io_plic_valid=%b",
                 pass_count + fail_count, rtl_io_plic_valid, dpi_io_plic_valid);
      end
    end

    // ── Summary ───────────────────────────────────────────────────────
    if (fail_count == 0) begin
      $display("[PASS] seed=%0d: %0d matches, 0 mismatches", seed, pass_count);
      $display("RESULT: PASS");
    end else begin
      $display("[FAIL] seed=%0d: %0d matches, %0d mismatches",
               seed, pass_count, fail_count);
      $display("RESULT: FAIL %0d mismatches", fail_count);
      $fatal(1, "Co-simulation FAILED");
    end

    $finish;
  end

endmodule
