// AUTO-GENERATED by hirct-gen — DO NOT EDIT
`timescale 1ns/1ps

module tb_Fadu_K2_S5_Queue_11;

  // ── Parameters ────────────────────────────────────────────────────────
  int seed   = 42;
  int cycles = 1000;

  // ── Shared signals ────────────────────────────────────────────────────
  logic        preset_flops;
  logic        clk;
  logic        reset;
  logic        io_enq_valid;
  logic [10:0] io_enq_bits;
  logic        io_deq_ready;

  // ── RTL outputs ───────────────────────────────────────────────────────
  logic        rtl_io_enq_ready;
  logic        rtl_io_deq_valid;
  logic [10:0] rtl_io_deq_bits;

  // ── DPI outputs ───────────────────────────────────────────────────────
  logic        dpi_io_enq_ready;
  logic        dpi_io_deq_valid;
  logic [10:0] dpi_io_deq_bits;

  // ── RTL instance ──────────────────────────────────────────────────────
  Fadu_K2_S5_Queue_11 u_rtl (
    .preset_flops (preset_flops),
    .clock        (clk),
    .reset        (reset),
    .io_enq_ready (rtl_io_enq_ready),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_valid (rtl_io_deq_valid),
    .io_deq_bits  (rtl_io_deq_bits)
  );

  // ── DPI-C wrapper instance ────────────────────────────────────────────
  Fadu_K2_S5_Queue_11_dpi_wrapper u_dpi (
    .preset_flops (preset_flops),
    .clock        (clk),
    .reset        (reset),
    .io_enq_ready (dpi_io_enq_ready),
    .io_enq_valid (io_enq_valid),
    .io_enq_bits  (io_enq_bits),
    .io_deq_ready (io_deq_ready),
    .io_deq_valid (dpi_io_deq_valid),
    .io_deq_bits  (dpi_io_deq_bits)
  );

  // ── Clock generation (10 ns period) ───────────────────────────────────
  initial clk = 0;
  always #5 clk = ~clk;

  // ── Waveform dump (plusarg-controlled) ──────────────────────────────────
  initial begin
    reg [8*64-1:0] dump_fmt;
    if ($value$plusargs("dump=%s", dump_fmt)) begin
`ifdef VCS
      if (dump_fmt == "fsdb") begin
        $fsdbDumpfile("waves.fsdb");
        $fsdbDumpvars(0, tb_Fadu_K2_S5_Queue_11);
        $fsdbDumpMDA;
      end else
`endif
      if (dump_fmt == "vcd") begin
        $dumpfile("waves.vcd");
        $dumpvars(0, tb_Fadu_K2_S5_Queue_11);
      end
    end
  end

  // ── Main stimulus ─────────────────────────────────────────────────────
  int pass_count;
  int fail_count;
  int warmup;

  initial begin
    if ($value$plusargs("seed=%d", seed))   ;
    if ($value$plusargs("cycles=%d", cycles)) ;
    process::self().srandom(seed);

    pass_count = 0;
    fail_count = 0;
    warmup     = 10;

    // ── Reset phase ───────────────────────────────────────────────────
    preset_flops = 1;
    reset        = 1;
    io_enq_valid = 0;
    io_enq_bits  = 11'b0;
    io_deq_ready = 0;

    @(posedge clk);
    preset_flops = 0;

    repeat (9) @(posedge clk);
    reset = 0;

    // ── Warmup (10 cycles, no comparison) ─────────────────────────────
    repeat (warmup) begin
      @(posedge clk);
      io_enq_valid = $urandom_range(0, 1);
      io_enq_bits  = $urandom_range(0, 2047);
      io_deq_ready = $urandom_range(0, 1);
    end

    // ── Comparison phase ──────────────────────────────────────────────
    repeat (cycles) begin
      @(posedge clk);
      io_enq_valid = $urandom_range(0, 1);
      io_enq_bits  = $urandom_range(0, 2047);
      io_deq_ready = $urandom_range(0, 1);

      @(negedge clk);
      if (rtl_io_enq_ready === dpi_io_enq_ready &&
          rtl_io_deq_valid === dpi_io_deq_valid &&
          rtl_io_deq_bits  === dpi_io_deq_bits) begin
        pass_count++;
      end else begin
        fail_count++;
        $display("[MISMATCH] cyc=%0d: R(%b %b %0h) D(%b %b %0h)",
                 pass_count + fail_count,
                 rtl_io_enq_ready, rtl_io_deq_valid,
                 rtl_io_deq_bits,
                 dpi_io_enq_ready, dpi_io_deq_valid,
                 dpi_io_deq_bits);
      end
    end

    // ── Summary ───────────────────────────────────────────────────────
    if (fail_count == 0) begin
      $display("[PASS] seed=%0d: %0d matches, 0 mismatches", seed, pass_count);
      $display("RESULT: PASS");
    end else begin
      $display("[FAIL] seed=%0d: %0d matches, %0d mismatches",
               seed, pass_count, fail_count);
      $display("RESULT: FAIL %0d mismatches", fail_count);
      $fatal(1, "Co-simulation FAILED");
    end

    $finish;
  end

endmodule
