// AUTO-GENERATED by hirct-gen — DO NOT EDIT
`timescale 1ns/1ps

module tb_Fadu_K2_S5_CLINT;

  int seed   = 42;
  int cycles = 1000;

  // ── Shared signals (inputs) ────────────────────────────────────────────
  logic        preset_flops;
  logic        clk;
  logic        reset;
  logic        auto_in_a_valid;
  logic [2:0]  auto_in_a_bits_opcode;
  logic [2:0]  auto_in_a_bits_param;
  logic [1:0]  auto_in_a_bits_size;
  logic [10:0] auto_in_a_bits_source;
  logic [31:0] auto_in_a_bits_address;
  logic [7:0]  auto_in_a_bits_mask;
  logic [63:0] auto_in_a_bits_data;
  logic        auto_in_a_bits_corrupt;
  logic        auto_in_d_ready;
  logic        io_rtcTick;

  // ── RTL outputs ────────────────────────────────────────────────────────
  logic        rtl_auto_int_out_0;
  logic        rtl_auto_int_out_1;
  logic        rtl_auto_in_a_ready;
  logic        rtl_auto_in_d_valid;
  logic [2:0]  rtl_auto_in_d_bits_opcode;
  logic [1:0]  rtl_auto_in_d_bits_size;
  logic [10:0] rtl_auto_in_d_bits_source;
  logic [63:0] rtl_auto_in_d_bits_data;

  // ── DPI outputs ────────────────────────────────────────────────────────
  logic        dpi_auto_int_out_0;
  logic        dpi_auto_int_out_1;
  logic        dpi_auto_in_a_ready;
  logic        dpi_auto_in_d_valid;
  logic [2:0]  dpi_auto_in_d_bits_opcode;
  logic [1:0]  dpi_auto_in_d_bits_size;
  logic [10:0] dpi_auto_in_d_bits_source;
  logic [63:0] dpi_auto_in_d_bits_data;

  // ── RTL instance ───────────────────────────────────────────────────────
  Fadu_K2_S5_CLINT u_rtl (
    .preset_flops          (preset_flops),
    .clock                 (clk),
    .reset                 (reset),
    .auto_int_out_0        (rtl_auto_int_out_0),
    .auto_int_out_1        (rtl_auto_int_out_1),
    .auto_in_a_ready       (rtl_auto_in_a_ready),
    .auto_in_a_valid       (auto_in_a_valid),
    .auto_in_a_bits_opcode (auto_in_a_bits_opcode),
    .auto_in_a_bits_param  (auto_in_a_bits_param),
    .auto_in_a_bits_size   (auto_in_a_bits_size),
    .auto_in_a_bits_source (auto_in_a_bits_source),
    .auto_in_a_bits_address(auto_in_a_bits_address),
    .auto_in_a_bits_mask   (auto_in_a_bits_mask),
    .auto_in_a_bits_data   (auto_in_a_bits_data),
    .auto_in_a_bits_corrupt(auto_in_a_bits_corrupt),
    .auto_in_d_ready       (auto_in_d_ready),
    .auto_in_d_valid       (rtl_auto_in_d_valid),
    .auto_in_d_bits_opcode (rtl_auto_in_d_bits_opcode),
    .auto_in_d_bits_size   (rtl_auto_in_d_bits_size),
    .auto_in_d_bits_source (rtl_auto_in_d_bits_source),
    .auto_in_d_bits_data   (rtl_auto_in_d_bits_data),
    .io_rtcTick            (io_rtcTick)
  );

  // ── DPI-C wrapper instance ─────────────────────────────────────────────
  Fadu_K2_S5_CLINT_dpi_wrapper u_dpi (
    .preset_flops          (preset_flops),
    .clock                 (clk),
    .reset                 (reset),
    .auto_int_out_0        (dpi_auto_int_out_0),
    .auto_int_out_1        (dpi_auto_int_out_1),
    .auto_in_a_ready       (dpi_auto_in_a_ready),
    .auto_in_a_valid       (auto_in_a_valid),
    .auto_in_a_bits_opcode (auto_in_a_bits_opcode),
    .auto_in_a_bits_param  (auto_in_a_bits_param),
    .auto_in_a_bits_size   (auto_in_a_bits_size),
    .auto_in_a_bits_source (auto_in_a_bits_source),
    .auto_in_a_bits_address(auto_in_a_bits_address),
    .auto_in_a_bits_mask   (auto_in_a_bits_mask),
    .auto_in_a_bits_data   (auto_in_a_bits_data),
    .auto_in_a_bits_corrupt(auto_in_a_bits_corrupt),
    .auto_in_d_ready       (auto_in_d_ready),
    .auto_in_d_valid       (dpi_auto_in_d_valid),
    .auto_in_d_bits_opcode (dpi_auto_in_d_bits_opcode),
    .auto_in_d_bits_size   (dpi_auto_in_d_bits_size),
    .auto_in_d_bits_source (dpi_auto_in_d_bits_source),
    .auto_in_d_bits_data   (dpi_auto_in_d_bits_data),
    .io_rtcTick            (io_rtcTick)
  );

  // ── Clock generation (10 ns period) ────────────────────────────────────
  initial clk = 0;
  always #5 clk = ~clk;

  // ── Waveform dump ──────────────────────────────────────────────────────
  initial begin
    string dump_fmt, dump_file;
    if ($value$plusargs("dump=%s", dump_fmt)) begin
      if (dump_fmt == "fsdb") begin
        if (!$value$plusargs("dump_file=%s", dump_file))
          dump_file = "waves.fsdb";
        $fsdbDumpfile(dump_file);
        $fsdbDumpvars(0, tb_Fadu_K2_S5_CLINT);
        $fsdbDumpMDA;
      end else if (dump_fmt == "vcd") begin
        if (!$value$plusargs("dump_file=%s", dump_file))
          dump_file = "waves.vcd";
        $dumpfile(dump_file);
        $dumpvars(0, tb_Fadu_K2_S5_CLINT);
      end
    end
  end

  // ── Main stimulus ──────────────────────────────────────────────────────
  int pass_count;
  int fail_count;
  int warmup;
  string first_mismatch_port;

  initial begin
    if ($value$plusargs("seed=%d", seed))   ;
    if ($value$plusargs("cycles=%d", cycles)) ;
    process::self().srandom(seed);

    pass_count = 0;
    fail_count = 0;
    warmup     = 20;
    first_mismatch_port = "";

    // ── Reset phase ──────────────────────────────────────────────────
    preset_flops          = 1;
    reset                 = 1;
    auto_in_a_valid       = 0;
    auto_in_a_bits_opcode = 0;
    auto_in_a_bits_param  = 0;
    auto_in_a_bits_size   = 0;
    auto_in_a_bits_source = 0;
    auto_in_a_bits_address= 0;
    auto_in_a_bits_mask   = 0;
    auto_in_a_bits_data   = 0;
    auto_in_a_bits_corrupt= 0;
    auto_in_d_ready       = 1;
    io_rtcTick            = 0;

    @(posedge clk);
    preset_flops = 0;
    repeat (9) @(posedge clk);
    reset = 0;

    // ── Warmup ───────────────────────────────────────────────────────
    repeat (warmup) begin
      @(posedge clk);
      io_rtcTick            = $urandom_range(0, 1);
      auto_in_a_valid       = $urandom_range(0, 1);
      auto_in_a_bits_opcode = $urandom_range(0, 4);
      auto_in_a_bits_size   = $urandom_range(0, 3);
      auto_in_a_bits_source = $urandom_range(0, 2047);
      auto_in_a_bits_address= $urandom;
      auto_in_a_bits_mask   = $urandom_range(0, 255);
      auto_in_a_bits_data   = {$urandom, $urandom};
      auto_in_d_ready       = $urandom_range(0, 1);
    end

    // ── Comparison phase ─────────────────────────────────────────────
    repeat (cycles) begin
      @(posedge clk);
      io_rtcTick            = $urandom_range(0, 1);
      auto_in_a_valid       = $urandom_range(0, 1);
      auto_in_a_bits_opcode = $urandom_range(0, 4);
      auto_in_a_bits_size   = $urandom_range(0, 3);
      auto_in_a_bits_source = $urandom_range(0, 2047);
      auto_in_a_bits_address= $urandom;
      auto_in_a_bits_mask   = $urandom_range(0, 255);
      auto_in_a_bits_data   = {$urandom, $urandom};
      auto_in_d_ready       = $urandom_range(0, 1);

      @(negedge clk);
      if (rtl_auto_int_out_0     !== dpi_auto_int_out_0 ||
          rtl_auto_int_out_1     !== dpi_auto_int_out_1 ||
          rtl_auto_in_a_ready    !== dpi_auto_in_a_ready ||
          rtl_auto_in_d_valid    !== dpi_auto_in_d_valid ||
          rtl_auto_in_d_bits_opcode !== dpi_auto_in_d_bits_opcode ||
          rtl_auto_in_d_bits_size   !== dpi_auto_in_d_bits_size ||
          rtl_auto_in_d_bits_source !== dpi_auto_in_d_bits_source ||
          rtl_auto_in_d_bits_data   !== dpi_auto_in_d_bits_data) begin
        fail_count++;
        if (fail_count <= 5) begin
          if (rtl_auto_int_out_0 !== dpi_auto_int_out_0)
            $display("[MISMATCH] cyc=%0d port=auto_int_out_0 RTL=%b DPI=%b",
                     pass_count+fail_count, rtl_auto_int_out_0, dpi_auto_int_out_0);
          if (rtl_auto_in_d_bits_data !== dpi_auto_in_d_bits_data)
            $display("[MISMATCH] cyc=%0d port=auto_in_d_bits_data RTL=%h DPI=%h",
                     pass_count+fail_count, rtl_auto_in_d_bits_data, dpi_auto_in_d_bits_data);
          if (rtl_auto_in_d_valid !== dpi_auto_in_d_valid)
            $display("[MISMATCH] cyc=%0d port=auto_in_d_valid RTL=%b DPI=%b",
                     pass_count+fail_count, rtl_auto_in_d_valid, dpi_auto_in_d_valid);
        end
      end else begin
        pass_count++;
      end
    end

    // ── Summary ──────────────────────────────────────────────────────
    if (fail_count == 0) begin
      $display("[PASS] seed=%0d: %0d matches, 0 mismatches", seed, pass_count);
      $display("RESULT: PASS");
    end else begin
      $display("[FAIL] seed=%0d: %0d matches, %0d mismatches",
               seed, pass_count, fail_count);
      $display("RESULT: FAIL %0d mismatches", fail_count);
      $fatal(1, "Co-simulation FAILED");
    end

    $finish;
  end

endmodule
